"""
T12 — PDF booklet merger (PyMuPDF).

זרימה:
  1. cover_page_bytes — בונה דף-שער A4 RTL הכולל פרטי החריג + ai_justification_text.
  2. download_pdfs   — async download של כל ה-attached_pdf_urls ל-BytesIO.
  3. merge_to_booklet — ממזג cover + כל ה-attachments למסמך אחד.
  4. upload_to_storage — העלאה לבאקט Supabase Storage והחזרת public URL.

PyMuPDF (fitz) משמש בלעדית בצד שרת — מהיר, ללא תלות ב-headless Chromium.
"""

from __future__ import annotations

import asyncio
import io
import logging
from typing import Any

import fitz  # PyMuPDF
import httpx

from config import settings

log = logging.getLogger("ai-worker.t12.pdf")

STORAGE_BUCKET = "variation-booklets"  # שונה בעת הצורך דרך env
COVER_FONT = "helv"  # PyMuPDF built-in (Helvetica)
HEBREW_NOTE = (
    "Note: PyMuPDF built-in fonts do not render Hebrew. "
    "Hebrew text is embedded RTL via insert_textbox using the default font; "
    "for production-grade Hebrew rendering, register a TTF (e.g. Noto Sans Hebrew) "
    "and pass it via fontfile= to insert_textbox."
)


class PdfMergeError(RuntimeError):
    """כשל בבניית/הורדת/מיזוג/העלאת ה-PDF."""


# ── 1) Cover page ────────────────────────────────────────────

def build_cover_page_bytes(
    *,
    variation_id: str,
    project_id: str,
    company_id: str,
    description: str,
    justification: str,
    rag_matches_count: int,
) -> bytes:
    """
    בונה PDF של דף אחד (A4) עם פרטי חריג + הצדקה.
    מחזיר bytes.
    """
    doc = fitz.open()
    page = doc.new_page(width=595, height=842)  # A4 portrait

    # Header
    page.insert_text(
        (50, 60),
        "Variation Order — Cover Booklet",
        fontname=COVER_FONT,
        fontsize=18,
    )
    page.insert_text(
        (50, 82),
        f"Variation ID: {variation_id}",
        fontname=COVER_FONT,
        fontsize=9,
    )
    page.insert_text(
        (50, 96),
        f"Project: {project_id}   |   Company: {company_id}",
        fontname=COVER_FONT,
        fontsize=9,
    )
    page.insert_text(
        (50, 110),
        f"RAG matches used: {rag_matches_count}",
        fontname=COVER_FONT,
        fontsize=9,
    )

    # Separator
    page.draw_line((50, 124), (545, 124), color=(0.2, 0.2, 0.2), width=0.7)

    # Description
    page.insert_text(
        (50, 146),
        "Field Description",
        fontname=COVER_FONT,
        fontsize=12,
    )
    page.insert_textbox(
        fitz.Rect(50, 154, 545, 280),
        description,
        fontname=COVER_FONT,
        fontsize=10,
        align=fitz.TEXT_ALIGN_LEFT,
    )

    # Justification (AI-generated)
    page.insert_text(
        (50, 300),
        "AI Justification (Contractor)",
        fontname=COVER_FONT,
        fontsize=12,
    )
    page.insert_textbox(
        fitz.Rect(50, 310, 545, 760),
        justification,
        fontname=COVER_FONT,
        fontsize=10.5,
        align=fitz.TEXT_ALIGN_LEFT,
    )

    # Footer
    page.insert_text(
        (50, 800),
        "Auto-generated by Smart Building OS — ai-worker T12",
        fontname=COVER_FONT,
        fontsize=7,
        color=(0.45, 0.45, 0.45),
    )

    out = io.BytesIO()
    doc.save(out, deflate=True, garbage=4)
    doc.close()
    return out.getvalue()


# ── 2) Download attached PDFs ────────────────────────────────

async def _download_one(client: httpx.AsyncClient, url: str) -> tuple[str, bytes]:
    """מוריד קובץ יחיד. מחזיר (url, bytes) או זורק."""
    resp = await client.get(url)
    resp.raise_for_status()
    return url, resp.content


async def download_pdfs(urls: list[str]) -> list[tuple[str, bytes]]:
    """async-מוריד את כל ה-PDFs במקביל. מדלג בשקט על URLs שנכשלים אך מלוגג."""
    if not urls:
        return []

    out: list[tuple[str, bytes]] = []
    async with httpx.AsyncClient(timeout=60.0, follow_redirects=True) as client:
        results = await asyncio.gather(
            *(_download_one(client, u) for u in urls),
            return_exceptions=True,
        )
        for u, res in zip(urls, results):
            if isinstance(res, BaseException):
                log.warning("[t12.pdf] failed downloading %s: %s", u, res)
                continue
            url, content = res  # type: ignore[misc]
            if not content:
                log.warning("[t12.pdf] empty content from %s", u)
                continue
            out.append((url, content))
    return out


# ── 3) Merge ─────────────────────────────────────────────────

def merge_to_booklet(
    cover_bytes: bytes,
    attachments: list[tuple[str, bytes]],
) -> tuple[bytes, int]:
    """
    ממזג cover + attachments למסמך PDF יחיד.
    מחזיר (bytes, total_pages).
    """
    booklet = fitz.open(stream=cover_bytes, filetype="pdf")
    total_pages = booklet.page_count

    for url, data in attachments:
        try:
            sub = fitz.open(stream=data, filetype="pdf")
        except Exception as exc:  # noqa: BLE001
            log.warning("[t12.pdf] skip non-PDF attachment %s: %s", url, exc)
            continue
        booklet.insert_pdf(sub)
        total_pages += sub.page_count
        sub.close()

    out = io.BytesIO()
    booklet.save(out, deflate=True, garbage=4)
    booklet.close()
    return out.getvalue(), total_pages


# ── 4) Upload to Supabase Storage ────────────────────────────

async def upload_to_storage(
    *,
    pdf_bytes: bytes,
    object_path: str,
    bucket: str = STORAGE_BUCKET,
) -> str:
    """
    מעלה קובץ ל-Supabase Storage באמצעות REST API (service-role).
    מחזיר public URL.

    object_path דוגמה: "<company_id>/<project_id>/<variation_id>.pdf"
    """
    if not settings.supabase_url or not settings.supabase_service_role_key:
        raise PdfMergeError("Supabase credentials missing for Storage upload.")

    url = f"{settings.supabase_url}/storage/v1/object/{bucket}/{object_path}"
    headers = {
        "Authorization": f"Bearer {settings.supabase_service_role_key}",
        "apikey": settings.supabase_service_role_key,
        "Content-Type": "application/pdf",
        # x-upsert: 'true' כדי לאפשר re-generate של חוברות
        "x-upsert": "true",
        "cache-control": "max-age=3600",
    }

    async with httpx.AsyncClient(timeout=60.0) as client:
        resp = await client.post(url, content=pdf_bytes, headers=headers)
        if resp.status_code not in (200, 201):
            raise PdfMergeError(
                f"Storage upload failed (status={resp.status_code}): "
                f"{resp.text[:300]}"
            )

    public_url = (
        f"{settings.supabase_url}/storage/v1/object/public/{bucket}/{object_path}"
    )
    log.info("[t12.pdf] uploaded booklet → %s (%d bytes)", public_url, len(pdf_bytes))
    return public_url


# ── Convenience composite ────────────────────────────────────

async def build_and_upload_booklet(
    *,
    variation_id: str,
    project_id: str,
    company_id: str,
    description: str,
    justification: str,
    attached_pdf_urls: list[str],
    rag_matches_count: int,
) -> dict[str, Any]:
    """
    pipeline שלם של PDF: cover → download → merge → upload.
    מחזיר {pdf_url, pages_merged}.
    """
    cover = build_cover_page_bytes(
        variation_id=variation_id,
        project_id=project_id,
        company_id=company_id,
        description=description,
        justification=justification,
        rag_matches_count=rag_matches_count,
    )
    attachments = await download_pdfs(attached_pdf_urls)
    merged_bytes, total_pages = merge_to_booklet(cover, attachments)
    object_path = f"{company_id}/{project_id}/{variation_id}.pdf"
    pdf_url = await upload_to_storage(
        pdf_bytes=merged_bytes,
        object_path=object_path,
    )
    return {"pdf_url": pdf_url, "pages_merged": total_pages}
