-- Bank reconciliations — ייבוא דפי בנק, התאמה לשורות יומן
-- Depends on public.gl_accounts, public.journal_lines

create extension if not exists "uuid-ossp";

-- ---------------------------------------------------------------------------
-- bank_statements — כותרת דף חשבון / דוח בנק
-- ---------------------------------------------------------------------------
create table if not exists public.bank_statements (
  id uuid primary key default uuid_generate_v4(),
  bank_account_id uuid not null
    references public.gl_accounts (id) on delete restrict,
  statement_date date not null,
  statement_number text,
  starting_balance numeric not null default 0,
  ending_balance numeric not null default 0,
  status text not null default 'open'
    constraint bank_statements_status_chk check (status in ('open', 'reconciled')),
  created_at timestamptz not null default now(),
  created_by uuid null references auth.users (id) on delete set null
);

create index if not exists bank_statements_bank_account_id_idx
  on public.bank_statements (bank_account_id);

create index if not exists bank_statements_statement_date_idx
  on public.bank_statements (statement_date desc);

comment on table public.bank_statements is
  'ייבוא דוח בנק — יתרות פתיחה/סגירה וסטטוס התאמה';

-- ---------------------------------------------------------------------------
-- bank_statement_lines — שורות תנועה מהבנק
-- ---------------------------------------------------------------------------
create table if not exists public.bank_statement_lines (
  id uuid primary key default uuid_generate_v4(),
  statement_id uuid not null
    references public.bank_statements (id) on delete cascade,
  transaction_date date not null,
  value_date date,
  reference_number text,
  description text,
  debit numeric not null default 0,
  credit numeric not null default 0,
  match_status text not null default 'unmatched'
    constraint bank_statement_lines_match_status_chk
      check (match_status in ('unmatched', 'partial', 'matched'))
);

create index if not exists bank_statement_lines_statement_id_idx
  on public.bank_statement_lines (statement_id);

create index if not exists bank_statement_lines_match_status_idx
  on public.bank_statement_lines (match_status)
  where match_status <> 'matched';

comment on column public.bank_statement_lines.debit is
  'יציאה מהבנק (חובה בצד הבנק לפי הגדרת המערכת)';

comment on column public.bank_statement_lines.credit is
  'כניסה לבנק';

-- ---------------------------------------------------------------------------
-- reconciliations — קבוצת התאמה (מספר ויזואלי, סוג, אישור)
-- ---------------------------------------------------------------------------
create table if not exists public.reconciliations (
  id uuid primary key default uuid_generate_v4(),
  reconciliation_number integer not null
    generated by default as identity,
  type text not null
    constraint reconciliations_type_chk
      check (type in ('bank', 'credit_card', 'customer_supplier')),
  status text not null default 'temporary'
    constraint reconciliations_status_chk
      check (status in ('temporary', 'approved')),
  created_at timestamptz not null default now(),
  created_by uuid null references auth.users (id) on delete set null
);

create index if not exists reconciliations_created_at_idx
  on public.reconciliations (created_at desc);

comment on table public.reconciliations is
  'התאמה — מספר רץ לתצוגה (Match #n), סוג וסטטוס';

comment on column public.reconciliations.reconciliation_number is
  'מספר סידורי לתצוגה (למשל Match #5)';

-- ---------------------------------------------------------------------------
-- reconciliation_lines — קישור שורת בנק ↔ שורת יומן
-- ---------------------------------------------------------------------------
create table if not exists public.reconciliation_lines (
  id uuid primary key default uuid_generate_v4(),
  reconciliation_id uuid not null
    references public.reconciliations (id) on delete cascade,
  bank_line_id uuid null
    references public.bank_statement_lines (id) on delete set null,
  journal_line_id uuid null
    references public.journal_lines (id) on delete set null,
  matched_amount numeric not null default 0,
  constraint reconciliation_lines_one_side_chk check (
    bank_line_id is not null or journal_line_id is not null
  )
);

create index if not exists reconciliation_lines_reconciliation_id_idx
  on public.reconciliation_lines (reconciliation_id);

create index if not exists reconciliation_lines_bank_line_id_idx
  on public.reconciliation_lines (bank_line_id)
  where bank_line_id is not null;

create index if not exists reconciliation_lines_journal_line_id_idx
  on public.reconciliation_lines (journal_line_id)
  where journal_line_id is not null;

comment on column public.reconciliation_lines.matched_amount is
  'סכום שהותאם בשורה זו (פיצול חלקי)';

-- ---------------------------------------------------------------------------
-- Helper functions
-- ---------------------------------------------------------------------------
create or replace function public.sum_reconciliation_matched_amount(
  p_reconciliation_id uuid
)
returns numeric
language sql
stable
as $$
  select coalesce(sum(matched_amount), 0)
  from public.reconciliation_lines
  where reconciliation_id = p_reconciliation_id;
$$;

comment on function public.sum_reconciliation_matched_amount(uuid) is
  'סכום matched_amount לכל שורות ההתאמה';

create or replace function public.count_bank_lines_by_match_status(
  p_statement_id uuid,
  p_match_status text
)
returns bigint
language sql
stable
as $$
  select count(*)::bigint
  from public.bank_statement_lines
  where statement_id = p_statement_id
    and match_status = p_match_status;
$$;

comment on function public.count_bank_lines_by_match_status(uuid, text) is
  'מונה שורות בנק לפי סטטוס התאמה בדוח נתון';

-- ---------------------------------------------------------------------------
-- Grants
-- ---------------------------------------------------------------------------
grant select, insert, update, delete on public.bank_statements to authenticated;
grant select, insert, update, delete on public.bank_statement_lines to authenticated;
grant select, insert, update, delete on public.reconciliations to authenticated;
grant select, insert, update, delete on public.reconciliation_lines to authenticated;

grant all on public.bank_statements to service_role;
grant all on public.bank_statement_lines to service_role;
grant all on public.reconciliations to service_role;
grant all on public.reconciliation_lines to service_role;

grant execute on function public.sum_reconciliation_matched_amount(uuid) to authenticated;
grant execute on function public.sum_reconciliation_matched_amount(uuid) to service_role;

grant execute on function public.count_bank_lines_by_match_status(uuid, text) to authenticated;
grant execute on function public.count_bank_lines_by_match_status(uuid, text) to service_role;
